/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.form.login;

import com.form.login.Ventanas.Ventana1;
import com.form.login.Ventanas.Ventana10;
import com.form.login.Ventanas.Ventana2;
import com.form.login.Ventanas.Ventana3;
import com.form.login.Ventanas.Ventana4;
import com.form.login.Ventanas.Ventana5;
import com.form.login.Ventanas.Ventana6;
import com.form.login.Ventanas.Ventana7;
import com.form.login.Ventanas.Ventana8;
import com.form.login.Ventanas.Ventana9;

/**
 *
 * @author lumel
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        opcion3 = new javax.swing.JButton();
        opcion1 = new javax.swing.JButton();
        opcion2 = new javax.swing.JButton();
        opcion6 = new javax.swing.JButton();
        opcion4 = new javax.swing.JButton();
        opcion5 = new javax.swing.JButton();
        opcion9 = new javax.swing.JButton();
        opcion7 = new javax.swing.JButton();
        opcion10 = new javax.swing.JButton();
        opcion8 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(500, 400));
        setMinimumSize(new java.awt.Dimension(500, 400));
        setName("Menu"); // NOI18N
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        opcion3.setText("Ventana 3");
        opcion3.setMaximumSize(new java.awt.Dimension(100, 50));
        opcion3.setMinimumSize(new java.awt.Dimension(100, 50));
        opcion3.setPreferredSize(new java.awt.Dimension(100, 50));
        opcion3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcion3ActionPerformed(evt);
            }
        });
        getContentPane().add(opcion3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 70, -1, -1));

        opcion1.setText("Ventana 1");
        opcion1.setMaximumSize(new java.awt.Dimension(100, 50));
        opcion1.setMinimumSize(new java.awt.Dimension(100, 50));
        opcion1.setName("Ventana"); // NOI18N
        opcion1.setPreferredSize(new java.awt.Dimension(100, 50));
        opcion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcion1ActionPerformed(evt);
            }
        });
        getContentPane().add(opcion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, -1));

        opcion2.setText("Ventana 2");
        opcion2.setMaximumSize(new java.awt.Dimension(100, 50));
        opcion2.setMinimumSize(new java.awt.Dimension(100, 50));
        opcion2.setPreferredSize(new java.awt.Dimension(100, 50));
        opcion2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcion2ActionPerformed(evt);
            }
        });
        getContentPane().add(opcion2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, -1, -1));

        opcion6.setText("Ventana 6");
        opcion6.setMaximumSize(new java.awt.Dimension(100, 50));
        opcion6.setMinimumSize(new java.awt.Dimension(100, 50));
        opcion6.setPreferredSize(new java.awt.Dimension(100, 50));
        opcion6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcion6ActionPerformed(evt);
            }
        });
        getContentPane().add(opcion6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, -1, -1));

        opcion4.setText("Ventana 4");
        opcion4.setMaximumSize(new java.awt.Dimension(100, 50));
        opcion4.setMinimumSize(new java.awt.Dimension(100, 50));
        opcion4.setPreferredSize(new java.awt.Dimension(100, 50));
        opcion4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcion4ActionPerformed(evt);
            }
        });
        getContentPane().add(opcion4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));

        opcion5.setText("Ventana 5");
        opcion5.setMaximumSize(new java.awt.Dimension(100, 50));
        opcion5.setMinimumSize(new java.awt.Dimension(100, 50));
        opcion5.setPreferredSize(new java.awt.Dimension(100, 50));
        opcion5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcion5ActionPerformed(evt);
            }
        });
        getContentPane().add(opcion5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, -1, -1));

        opcion9.setText("Ventana 9");
        opcion9.setMaximumSize(new java.awt.Dimension(100, 50));
        opcion9.setMinimumSize(new java.awt.Dimension(100, 50));
        opcion9.setPreferredSize(new java.awt.Dimension(100, 50));
        opcion9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcion9ActionPerformed(evt);
            }
        });
        getContentPane().add(opcion9, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 210, -1, -1));

        opcion7.setText("Ventana 7");
        opcion7.setMaximumSize(new java.awt.Dimension(100, 50));
        opcion7.setMinimumSize(new java.awt.Dimension(100, 50));
        opcion7.setPreferredSize(new java.awt.Dimension(100, 50));
        opcion7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcion7ActionPerformed(evt);
            }
        });
        getContentPane().add(opcion7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, -1));

        opcion10.setText("Ventana 10");
        opcion10.setMaximumSize(new java.awt.Dimension(100, 50));
        opcion10.setMinimumSize(new java.awt.Dimension(100, 50));
        opcion10.setPreferredSize(new java.awt.Dimension(100, 50));
        opcion10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcion10ActionPerformed(evt);
            }
        });
        getContentPane().add(opcion10, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, -1, -1));

        opcion8.setText("Ventana 8");
        opcion8.setMaximumSize(new java.awt.Dimension(100, 50));
        opcion8.setMinimumSize(new java.awt.Dimension(100, 50));
        opcion8.setPreferredSize(new java.awt.Dimension(100, 50));
        opcion8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcion8ActionPerformed(evt);
            }
        });
        getContentPane().add(opcion8, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, -1, -1));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MENÚ DE OPCIONES");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 70));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void opcion8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcion8ActionPerformed
        Ventana8 v8 = new Ventana8();
        v8.setVisible(true);
    }//GEN-LAST:event_opcion8ActionPerformed

    private void opcion10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcion10ActionPerformed
        Ventana10 v10 = new Ventana10();
        v10.setVisible(true);
    }//GEN-LAST:event_opcion10ActionPerformed

    private void opcion7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcion7ActionPerformed
        Ventana7 v7 = new Ventana7();
        v7.setVisible(true);
    }//GEN-LAST:event_opcion7ActionPerformed

    private void opcion9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcion9ActionPerformed
        Ventana9 v9 = new Ventana9();
        v9.setVisible(true);
    }//GEN-LAST:event_opcion9ActionPerformed

    private void opcion5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcion5ActionPerformed
        Ventana5 v5 = new Ventana5();
        v5.setVisible(true);
    }//GEN-LAST:event_opcion5ActionPerformed

    private void opcion4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcion4ActionPerformed
        Ventana4 v4 = new Ventana4();
        v4.setVisible(true);
    }//GEN-LAST:event_opcion4ActionPerformed

    private void opcion6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcion6ActionPerformed
        Ventana6 v6 = new Ventana6();
        v6.setVisible(true);
    }//GEN-LAST:event_opcion6ActionPerformed

    private void opcion2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcion2ActionPerformed
        Ventana2 v2 = new Ventana2();
        v2.setVisible(true);
    }//GEN-LAST:event_opcion2ActionPerformed

    private void opcion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcion1ActionPerformed
        Ventana1 v1 = new Ventana1();
        v1.setVisible(true);
    }//GEN-LAST:event_opcion1ActionPerformed

    private void opcion3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcion3ActionPerformed
        Ventana3 v3 = new Ventana3();
        v3.setVisible(true);
    }//GEN-LAST:event_opcion3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton opcion1;
    private javax.swing.JButton opcion10;
    private javax.swing.JButton opcion2;
    private javax.swing.JButton opcion3;
    private javax.swing.JButton opcion4;
    private javax.swing.JButton opcion5;
    private javax.swing.JButton opcion6;
    private javax.swing.JButton opcion7;
    private javax.swing.JButton opcion8;
    private javax.swing.JButton opcion9;
    // End of variables declaration//GEN-END:variables
}
